# Generated by Django 5.1 on 2024-08-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcard',
            name='image',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
