# Generated by Django 5.1 on 2024-08-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_foodcategory_alter_foodcard_image_foodcard_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodcategory',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='foodcard',
            name='sostav',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
