# Generated by Django 5.1 on 2024-09-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_foodcard_description_alter_foodcard_sostav'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcard',
            name='display_sostav',
            field=models.BooleanField(default=True),
        ),
    ]
